services:
  dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ..:/workspace

volumes:
  postgres_data:
