name: app

on:
  pull_request:
    paths:
      - ./src/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          commant: fmt
          args: --all -- --check

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
